modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"

[[mods]]
modId = "itemtaker"
version = "${version}"
displayName = "ItemTaker"
authors = "VMStudio"
displayTest = "NONE"
description = '''
Item Taker for Visor

'''

[[dependencies.itemtaker]]
modId = "visor"
mandatory = true
versionRange = "[0.2.0-alpha,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.itemtaker]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.itemtaker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "AFTER"
side = "BOTH"
